### ISSUE TITLE
windows protoc compiler install 

### ISSUE THREAD

**Issue by AbdelrahmanHamdy1996** [simplesteph/protobuf-example-python#3]
greetings, I have a problem setup the compiler protocol I just followed all the steps and installed protobuf but the cmd can't recognize the protocol as result I can't continue the course or practice on the next subjects, any suggestion? or short video for steps live?

**Comment by AbdelrahmanHamdy1996** [comment]
![Capture](https://user-images.githubusercontent.com/46800696/55506399-a3185300-5655-11e9-9fd7-75385f3ac83a.PNG)

**Comment by simplesteph** [comment]
Make sure the 'protoc' is included in your path, wherever you have installed it

https://docs.alfresco.com/4.2/tasks/fot-addpath.html
